# Generated by Django 2.0 on 2017-12-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=140)),
                ('BTC', models.FloatField()),
                ('ETH', models.FloatField()),
                ('NEM', models.FloatField()),
                ('XZC', models.FloatField()),
            ],
        ),
    ]
