# Generated by Django 2.0.5 on 2018-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=250)),
                ('note_body', models.CharField(max_length=1000)),
                ('note_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
