# Generated by Django 2.0 on 2018-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalID', models.IntegerField()),
                ('orderCreationTime', models.CharField(max_length=120)),
                ('merchantID', models.IntegerField()),
                ('status', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=120)),
                ('orderID', models.TextField()),
                ('orderType', models.CharField(max_length=120)),
                ('orderDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
