# Generated by Django 2.0.7 on 2018-07-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180729_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='color',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stock',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight_per_package',
            field=models.IntegerField(default=0),
        ),
    ]
